// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'group-title': string;
  groupTitle: string;
}
export const cssExports: CssExports;
export default cssExports;
