// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'android-container': string;
  androidContainer: string;
  'img-container': string;
  imgContainer: string;
  'ios-container': string;
  iosContainer: string;
  'qrcode-card': string;
  'qrcode-container': string;
  qrcodeCard: string;
  qrcodeContainer: string;
  release: string;
}
export const cssExports: CssExports;
export default cssExports;
