// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'test-env': string;
  testEnv: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
