// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo-container': string;
  logoContainer: string;
  root: string;
  'site-layout': string;
  'site-layout-background': string;
  siteLayout: string;
  siteLayoutBackground: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
